// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConfig():Promise<main.Config>;

export function GetSettingsInfo():Promise<Record<string, string>>;

export function GetSystemInfo():Promise<Record<string, string>>;

export function LaunchClaude():Promise<string>;

export function RestoreNow():Promise<string>;

export function SelectDirectory():Promise<string>;

export function SetConfig(arg1:string,arg2:string,arg3:string):Promise<void>;
